services:
  confide:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    # volumes:
    #   - /etc/dokploy/traefik/dynamic:/traefik-config
    # env_file:
    #   - .env
    environment:
      CONFIDE_DATABASE_URL: postgresql://confide:confide@db:5432/confide
      CONFIDE_EDITION: community
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/api", "--health-check"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:18-alpine
    restart: always 
    environment:
      POSTGRES_USER: confide
      POSTGRES_PASSWORD: confide
      POSTGRES_DB: confide
    volumes:
      - confide-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  confide-db-data:
