// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const burnRecoveryCode = `-- name: BurnRecoveryCode :exec
UPDATE recovery_codes SET used = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) BurnRecoveryCode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, burnRecoveryCode, id)
	return err
}

const countCredentialsByAccount = `-- name: CountCredentialsByAccount :one
SELECT COUNT(*) FROM credentials WHERE account_id = $1
`

func (q *Queries) CountCredentialsByAccount(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentialsByAccount, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM recovery_codes WHERE account_id = $1 AND used = FALSE
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, created_at, recovery_wrapped_master, recovery_verifier, username
) VALUES (
    $1, NOW(), $2, $3, $4
) RETURNING id, created_at, recovery_wrapped_master, recovery_verifier, username, updated_at
`

type CreateAccountParams struct {
	ID                    string
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
	Username              pgtype.Text
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.RecoveryWrappedMaster,
		arg.RecoveryVerifier,
		arg.Username,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
		&i.Username,
		&i.UpdatedAt,
	)
	return i, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, account_id, credential_id, public_key, prf_salt,
    wrapped_master_key, backup_eligible, name, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
RETURNING id, account_id, credential_id, public_key, prf_salt, wrapped_master_key, backup_eligible, name, created_at, updated_at
`

type CreateCredentialParams struct {
	ID               string
	AccountID        string
	CredentialID     []byte
	PublicKey        []byte
	PrfSalt          []byte
	WrappedMasterKey []byte
	BackupEligible   bool
	Name             string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.AccountID,
		arg.CredentialID,
		arg.PublicKey,
		arg.PrfSalt,
		arg.WrappedMasterKey,
		arg.BackupEligible,
		arg.Name,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.PublicKey,
		&i.PrfSalt,
		&i.WrappedMasterKey,
		&i.BackupEligible,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type CreateRecoveryCodesParams struct {
	ID        string
	AccountID string
	CodeHash  []byte
	Used      bool
	CreatedAt pgtype.Timestamptz
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, account_id, token_hash, created_at, last_seen, credential_id, user_agent)
VALUES ($1, $2, $3, NOW(), NOW(), $4, $5)
RETURNING id, account_id, token_hash, created_at, last_seen, credential_id, user_agent, updated_at
`

type CreateSessionParams struct {
	ID           string
	AccountID    string
	TokenHash    []byte
	CredentialID []byte
	UserAgent    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.CredentialID,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeen,
		&i.CredentialID,
		&i.UserAgent,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = $1 AND account_id = $2
`

type DeleteCredentialParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteCredential, arg.ID, arg.AccountID)
	return err
}

const deleteCredentialsByAccount = `-- name: DeleteCredentialsByAccount :exec
DELETE FROM credentials WHERE account_id = $1
`

func (q *Queries) DeleteCredentialsByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteCredentialsByAccount, accountID)
	return err
}

const deleteRecoveryCodesByAccount = `-- name: DeleteRecoveryCodesByAccount :exec
DELETE FROM recovery_codes WHERE account_id=$1
`

func (q *Queries) DeleteRecoveryCodesByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByAccount, accountID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1 AND account_id = $2
`

type DeleteSessionParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.AccountID)
	return err
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :exec
DELETE FROM sessions WHERE account_id = $1 AND id != $2
`

type DeleteOtherSessionsParams struct {
	AccountID string
	ID        string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherSessions, arg.AccountID, arg.ID)
	return err
}

const deleteStaleSessions = `-- name: DeleteStaleSessions :exec
DELETE FROM sessions
WHERE last_seen <= NOW() - INTERVAL '14 days'
   OR created_at <= NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteStaleSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStaleSessions)
	return err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, recovery_wrapped_master, recovery_verifier, username, updated_at FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
		&i.Username,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUsername = `-- name: GetAccountByUsername :one
SELECT id, created_at, recovery_wrapped_master, recovery_verifier, username, updated_at FROM accounts WHERE username = $1
`

func (q *Queries) GetAccountByUsername(ctx context.Context, username pgtype.Text) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByUsername, username)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
		&i.Username,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPrfSalts = `-- name: GetAllPrfSalts :many
SELECT credential_id, prf_salt FROM credentials
`

type GetAllPrfSaltsRow struct {
	CredentialID []byte
	PrfSalt      []byte
}

func (q *Queries) GetAllPrfSalts(ctx context.Context) ([]GetAllPrfSaltsRow, error) {
	rows, err := q.db.Query(ctx, getAllPrfSalts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPrfSaltsRow
	for rows.Next() {
		var i GetAllPrfSaltsRow
		if err := rows.Scan(&i.CredentialID, &i.PrfSalt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialByWebAuthnID = `-- name: GetCredentialByWebAuthnID :one
SELECT c.id, c.account_id, c.credential_id, c.public_key, c.prf_salt,
       c.wrapped_master_key, c.backup_eligible, c.name, c.created_at,
       a.recovery_wrapped_master, a.recovery_verifier, a.username
FROM credentials c
JOIN accounts a ON a.id = c.account_id
WHERE c.credential_id = $1
`

type GetCredentialByWebAuthnIDRow struct {
	ID                    string
	AccountID             string
	CredentialID          []byte
	PublicKey             []byte
	PrfSalt               []byte
	WrappedMasterKey      []byte
	BackupEligible        bool
	Name                  string
	CreatedAt             pgtype.Timestamptz
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
	Username              pgtype.Text
}

func (q *Queries) GetCredentialByWebAuthnID(ctx context.Context, credentialID []byte) (GetCredentialByWebAuthnIDRow, error) {
	row := q.db.QueryRow(ctx, getCredentialByWebAuthnID, credentialID)
	var i GetCredentialByWebAuthnIDRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CredentialID,
		&i.PublicKey,
		&i.PrfSalt,
		&i.WrappedMasterKey,
		&i.BackupEligible,
		&i.Name,
		&i.CreatedAt,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
		&i.Username,
	)
	return i, err
}

const getCredentialForLogin = `-- name: GetCredentialForLogin :one
SELECT c.wrapped_master_key, c.prf_salt, c.account_id
FROM credentials c
WHERE c.credential_id = $1
`

type GetCredentialForLoginRow struct {
	WrappedMasterKey []byte
	PrfSalt          []byte
	AccountID        string
}

func (q *Queries) GetCredentialForLogin(ctx context.Context, credentialID []byte) (GetCredentialForLoginRow, error) {
	row := q.db.QueryRow(ctx, getCredentialForLogin, credentialID)
	var i GetCredentialForLoginRow
	err := row.Scan(&i.WrappedMasterKey, &i.PrfSalt, &i.AccountID)
	return i, err
}

const getPrimaryCredentialByAccount = `-- name: GetPrimaryCredentialByAccount :one
SELECT prf_salt FROM credentials
WHERE account_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetPrimaryCredentialByAccount(ctx context.Context, accountID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrimaryCredentialByAccount, accountID)
	var prf_salt []byte
	err := row.Scan(&prf_salt)
	return prf_salt, err
}

const getPrimaryCredentialIDByAccount = `-- name: GetPrimaryCredentialIDByAccount :one
SELECT credential_id FROM credentials
WHERE account_id = $1
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetPrimaryCredentialIDByAccount(ctx context.Context, accountID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPrimaryCredentialIDByAccount, accountID)
	var credential_id []byte
	err := row.Scan(&credential_id)
	return credential_id, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.account_id, s.token_hash, s.created_at, s.last_seen, c.wrapped_master_key
FROM sessions s
JOIN credentials c ON c.credential_id = s.credential_id
WHERE s.token_hash = $1
  AND s.last_seen > NOW() - INTERVAL '14 days'
  AND s.created_at > NOW() - INTERVAL '30 days'
`

type GetSessionByTokenHashRow struct {
	ID               string
	AccountID        string
	TokenHash        []byte
	CreatedAt        pgtype.Timestamptz
	LastSeen         pgtype.Timestamptz
	WrappedMasterKey []byte
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeen,
		&i.WrappedMasterKey,
	)
	return i, err
}

const getUnusedRecoveryCode = `-- name: GetUnusedRecoveryCode :one
SELECT id, account_id, code_hash, used, created_at, updated_at FROM recovery_codes
WHERE account_id = $1 AND code_hash = $2 AND used = FALSE
LIMIT 1
`

type GetUnusedRecoveryCodeParams struct {
	AccountID string
	CodeHash  []byte
}

func (q *Queries) GetUnusedRecoveryCode(ctx context.Context, arg GetUnusedRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, getUnusedRecoveryCode, arg.AccountID, arg.CodeHash)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CodeHash,
		&i.Used,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCredentialsByAccount = `-- name: ListCredentialsByAccount :many
SELECT id, account_id, credential_id, backup_eligible, name, created_at
FROM credentials
WHERE account_id = $1
ORDER BY created_at ASC
`

type ListCredentialsByAccountRow struct {
	ID             string
	AccountID      string
	CredentialID   []byte
	BackupEligible bool
	Name           string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListCredentialsByAccount(ctx context.Context, accountID string) ([]ListCredentialsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listCredentialsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsByAccountRow
	for rows.Next() {
		var i ListCredentialsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CredentialID,
			&i.BackupEligible,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedWorkspacesForDeletion = `-- name: ListOwnedWorkspacesForDeletion :many
SELECT w.id, w.stripe_subscription_id
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.account_id = $1 AND wm.role = 'owner'
`

type ListOwnedWorkspacesForDeletionRow struct {
	ID                   string
	StripeSubscriptionID pgtype.Text
}

func (q *Queries) ListOwnedWorkspacesForDeletion(ctx context.Context, accountID string) ([]ListOwnedWorkspacesForDeletionRow, error) {
	rows, err := q.db.Query(ctx, listOwnedWorkspacesForDeletion, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOwnedWorkspacesForDeletionRow
	for rows.Next() {
		var i ListOwnedWorkspacesForDeletionRow
		if err := rows.Scan(&i.ID, &i.StripeSubscriptionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByAccount = `-- name: ListSessionsByAccount :many
SELECT id, created_at, last_seen, credential_id, user_agent FROM sessions WHERE account_id = $1
`

type ListSessionsByAccountRow struct {
	ID           string
	CreatedAt    pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
	CredentialID []byte
	UserAgent    string
}

func (q *Queries) ListSessionsByAccount(ctx context.Context, accountID string) ([]ListSessionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByAccountRow
	for rows.Next() {
		var i ListSessionsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastSeen,
			&i.CredentialID,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateAccountRecovery = `-- name: UpdateAccountRecovery :exec
UPDATE accounts SET recovery_wrapped_master=$2, recovery_verifier=$3, updated_at=NOW() WHERE id=$1
`

type UpdateAccountRecoveryParams struct {
	ID                    string
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
}

func (q *Queries) UpdateAccountRecovery(ctx context.Context, arg UpdateAccountRecoveryParams) error {
	_, err := q.db.Exec(ctx, updateAccountRecovery, arg.ID, arg.RecoveryWrappedMaster, arg.RecoveryVerifier)
	return err
}

const updateCredentialBackupEligible = `-- name: UpdateCredentialBackupEligible :exec
UPDATE credentials SET backup_eligible = $2, updated_at = NOW() WHERE credential_id = $1
`

type UpdateCredentialBackupEligibleParams struct {
	CredentialID   []byte
	BackupEligible bool
}

func (q *Queries) UpdateCredentialBackupEligible(ctx context.Context, arg UpdateCredentialBackupEligibleParams) error {
	_, err := q.db.Exec(ctx, updateCredentialBackupEligible, arg.CredentialID, arg.BackupEligible)
	return err
}

const updateCredentialName = `-- name: UpdateCredentialName :exec
UPDATE credentials SET name = $3, updated_at = NOW()
WHERE id = $1 AND account_id = $2
`

type UpdateCredentialNameParams struct {
	ID        string
	AccountID string
	Name      string
}

func (q *Queries) UpdateCredentialName(ctx context.Context, arg UpdateCredentialNameParams) error {
	_, err := q.db.Exec(ctx, updateCredentialName, arg.ID, arg.AccountID, arg.Name)
	return err
}
