// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const burnRecoveryCode = `-- name: BurnRecoveryCode :exec
UPDATE recovery_codes SET used = TRUE WHERE id = $1
`

func (q *Queries) BurnRecoveryCode(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, burnRecoveryCode, id)
	return err
}

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM recovery_codes WHERE account_id = $1 AND used = FALSE
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    id, created_at, credential_id, public_key, prf_salt,
    wrapped_master_key, recovery_wrapped_master, recovery_verifier
) VALUES (
    $1, CURRENT_DATE, $2, $3, $4, $5, $6, $7
) RETURNING id, created_at, credential_id, public_key, prf_salt, wrapped_master_key, recovery_wrapped_master, recovery_verifier
`

type CreateAccountParams struct {
	ID                    string
	CredentialID          []byte
	PublicKey             []byte
	PrfSalt               []byte
	WrappedMasterKey      []byte
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.CredentialID,
		arg.PublicKey,
		arg.PrfSalt,
		arg.WrappedMasterKey,
		arg.RecoveryWrappedMaster,
		arg.RecoveryVerifier,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CredentialID,
		&i.PublicKey,
		&i.PrfSalt,
		&i.WrappedMasterKey,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
	)
	return i, err
}

type CreateRecoveryCodesParams struct {
	ID        string
	AccountID string
	CodeHash  []byte
	Used      bool
	CreatedAt pgtype.Date
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, account_id, token_hash, created_at, last_seen)
VALUES ($1, $2, $3, CURRENT_DATE, CURRENT_DATE)
RETURNING id, account_id, token_hash, created_at, last_seen
`

type CreateSessionParams struct {
	ID        string
	AccountID string
	TokenHash []byte
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.AccountID, arg.TokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const deleteRecoveryCodesByAccount = `-- name: DeleteRecoveryCodesByAccount :exec
DELETE FROM recovery_codes WHERE account_id=$1
`

func (q *Queries) DeleteRecoveryCodesByAccount(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByAccount, accountID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getAccountByCredentialID = `-- name: GetAccountByCredentialID :one
SELECT id, created_at, credential_id, public_key, prf_salt, wrapped_master_key, recovery_wrapped_master, recovery_verifier FROM accounts WHERE credential_id = $1
`

func (q *Queries) GetAccountByCredentialID(ctx context.Context, credentialID []byte) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCredentialID, credentialID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CredentialID,
		&i.PublicKey,
		&i.PrfSalt,
		&i.WrappedMasterKey,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, created_at, credential_id, public_key, prf_salt, wrapped_master_key, recovery_wrapped_master, recovery_verifier FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.CredentialID,
		&i.PublicKey,
		&i.PrfSalt,
		&i.WrappedMasterKey,
		&i.RecoveryWrappedMaster,
		&i.RecoveryVerifier,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.account_id, s.token_hash, s.created_at, s.last_seen, a.wrapped_master_key
FROM sessions s
JOIN accounts a ON a.id = s.account_id
WHERE s.token_hash = $1
  AND s.last_seen > CURRENT_DATE - INTERVAL '30 days'
`

type GetSessionByTokenHashRow struct {
	ID               string
	AccountID        string
	TokenHash        []byte
	CreatedAt        pgtype.Date
	LastSeen         pgtype.Date
	WrappedMasterKey []byte
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastSeen,
		&i.WrappedMasterKey,
	)
	return i, err
}

const getUnusedRecoveryCode = `-- name: GetUnusedRecoveryCode :one
SELECT id, account_id, code_hash, used, created_at FROM recovery_codes
WHERE account_id = $1 AND code_hash = $2 AND used = FALSE
LIMIT 1
`

type GetUnusedRecoveryCodeParams struct {
	AccountID string
	CodeHash  []byte
}

func (q *Queries) GetUnusedRecoveryCode(ctx context.Context, arg GetUnusedRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, getUnusedRecoveryCode, arg.AccountID, arg.CodeHash)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CodeHash,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const listSessionsByAccount = `-- name: ListSessionsByAccount :many
SELECT id, created_at, last_seen FROM sessions WHERE account_id = $1
`

type ListSessionsByAccountRow struct {
	ID        string
	CreatedAt pgtype.Date
	LastSeen  pgtype.Date
}

func (q *Queries) ListSessionsByAccount(ctx context.Context, accountID string) ([]ListSessionsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listSessionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByAccountRow
	for rows.Next() {
		var i ListSessionsByAccountRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen = CURRENT_DATE WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateAccountCredential = `-- name: UpdateAccountCredential :exec
UPDATE accounts SET credential_id=$2, public_key=$3, prf_salt=$4,
    wrapped_master_key=$5, recovery_wrapped_master=$6, recovery_verifier=$7 WHERE id=$1
`

type UpdateAccountCredentialParams struct {
	ID                    string
	CredentialID          []byte
	PublicKey             []byte
	PrfSalt               []byte
	WrappedMasterKey      []byte
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
}

func (q *Queries) UpdateAccountCredential(ctx context.Context, arg UpdateAccountCredentialParams) error {
	_, err := q.db.Exec(ctx, updateAccountCredential,
		arg.ID,
		arg.CredentialID,
		arg.PublicKey,
		arg.PrfSalt,
		arg.WrappedMasterKey,
		arg.RecoveryWrappedMaster,
		arg.RecoveryVerifier,
	)
	return err
}
