// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFormsByWorkspace = `-- name: CountFormsByWorkspace :one
SELECT COUNT(*) FROM forms WHERE workspace_id = $1
`

func (q *Queries) CountFormsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFormsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMonthlyResponses = `-- name: CountMonthlyResponses :one
SELECT COUNT(*)
FROM responses r
JOIN forms f ON f.id = r.form_id
WHERE f.workspace_id = $1
  AND r.received_at >= date_trunc('month', NOW())
`

func (q *Queries) CountMonthlyResponses(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countMonthlyResponses, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkspaceByStripeCustomerID = `-- name: GetWorkspaceByStripeCustomerID :one
SELECT id, plan, plan_status
FROM workspaces WHERE stripe_customer_id = $1
`

type GetWorkspaceByStripeCustomerIDRow struct {
	ID         string
	Plan       string
	PlanStatus string
}

func (q *Queries) GetWorkspaceByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (GetWorkspaceByStripeCustomerIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByStripeCustomerID, stripeCustomerID)
	var i GetWorkspaceByStripeCustomerIDRow
	err := row.Scan(&i.ID, &i.Plan, &i.PlanStatus)
	return i, err
}

const getWorkspaceForBilling = `-- name: GetWorkspaceForBilling :one
SELECT id, name, plan, plan_status, plan_period_end, stripe_customer_id, stripe_subscription_id
FROM workspaces WHERE id = $1
`

type GetWorkspaceForBillingRow struct {
	ID                   string
	Name                 string
	Plan                 string
	PlanStatus           string
	PlanPeriodEnd        pgtype.Timestamptz
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
}

func (q *Queries) GetWorkspaceForBilling(ctx context.Context, id string) (GetWorkspaceForBillingRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceForBilling, id)
	var i GetWorkspaceForBillingRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
	)
	return i, err
}

const setStripeCustomerID = `-- name: SetStripeCustomerID :exec
UPDATE workspaces SET stripe_customer_id = $2, updated_at = NOW() WHERE id = $1
`

type SetStripeCustomerIDParams struct {
	ID               string
	StripeCustomerID pgtype.Text
}

func (q *Queries) SetStripeCustomerID(ctx context.Context, arg SetStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, setStripeCustomerID, arg.ID, arg.StripeCustomerID)
	return err
}

const updateWorkspacePlan = `-- name: UpdateWorkspacePlan :exec
UPDATE workspaces
SET plan            = $2,
    plan_status     = $3,
    plan_period_end = $4,
    updated_at      = NOW()
WHERE id = $1
`

type UpdateWorkspacePlanParams struct {
	ID            string
	Plan          string
	PlanStatus    string
	PlanPeriodEnd pgtype.Timestamptz
}

func (q *Queries) UpdateWorkspacePlan(ctx context.Context, arg UpdateWorkspacePlanParams) error {
	_, err := q.db.Exec(ctx, updateWorkspacePlan,
		arg.ID,
		arg.Plan,
		arg.PlanStatus,
		arg.PlanPeriodEnd,
	)
	return err
}
