// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateRecoveryCodes implements pgx.CopyFromSource.
type iteratorForCreateRecoveryCodes struct {
	rows                 []CreateRecoveryCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateRecoveryCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateRecoveryCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].AccountID,
		r.rows[0].CodeHash,
		r.rows[0].Used,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCreateRecoveryCodes) Err() error {
	return nil
}

func (q *Queries) CreateRecoveryCodes(ctx context.Context, arg []CreateRecoveryCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"recovery_codes"}, []string{"id", "account_id", "code_hash", "used", "created_at"}, &iteratorForCreateRecoveryCodes{rows: arg})
}
