// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (
    id, workspace_id, created_by_account_id, created_at, updated_at, status, schema_version,
    response_count, encrypted_schema, render_encrypted_schema, public_form_key,
    render_key_salt, expires_at, response_limit, response_ttl_days, burn_after_reading,
    workspace_wrapped_form_key
) VALUES (
    $1, $2, $3, NOW(), NOW(), 'open', 1, 0, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, created_at, updated_at, status, schema_version, response_count, encrypted_schema, render_encrypted_schema, public_form_key, render_key_salt, expires_at, response_limit, response_ttl_days, burn_after_reading, workspace_id, created_by_account_id, workspace_wrapped_form_key, use_custom_domain
`

type CreateFormParams struct {
	ID                      string
	WorkspaceID             string
	CreatedByAccountID      string
	EncryptedSchema         []byte
	RenderEncryptedSchema   []byte
	PublicFormKey           []byte
	RenderKeySalt           []byte
	ExpiresAt               pgtype.Date
	ResponseLimit           pgtype.Int4
	ResponseTtlDays         pgtype.Int4
	BurnAfterReading        bool
	WorkspaceWrappedFormKey []byte
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedByAccountID,
		arg.EncryptedSchema,
		arg.RenderEncryptedSchema,
		arg.PublicFormKey,
		arg.RenderKeySalt,
		arg.ExpiresAt,
		arg.ResponseLimit,
		arg.ResponseTtlDays,
		arg.BurnAfterReading,
		arg.WorkspaceWrappedFormKey,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.SchemaVersion,
		&i.ResponseCount,
		&i.EncryptedSchema,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
		&i.RenderKeySalt,
		&i.ExpiresAt,
		&i.ResponseLimit,
		&i.ResponseTtlDays,
		&i.BurnAfterReading,
		&i.WorkspaceID,
		&i.CreatedByAccountID,
		&i.WorkspaceWrappedFormKey,
		&i.UseCustomDomain,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = $1 AND workspace_id = $2
`

type DeleteFormParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) error {
	_, err := q.db.Exec(ctx, deleteForm, arg.ID, arg.WorkspaceID)
	return err
}

const getFormByWorkspace = `-- name: GetFormByWorkspace :one
SELECT id, created_at, updated_at, status, schema_version, response_count, encrypted_schema, render_encrypted_schema, public_form_key, render_key_salt, expires_at, response_limit, response_ttl_days, burn_after_reading, workspace_id, created_by_account_id, workspace_wrapped_form_key, use_custom_domain FROM forms WHERE id = $1 AND workspace_id = $2
`

type GetFormByWorkspaceParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) GetFormByWorkspace(ctx context.Context, arg GetFormByWorkspaceParams) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByWorkspace, arg.ID, arg.WorkspaceID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.SchemaVersion,
		&i.ResponseCount,
		&i.EncryptedSchema,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
		&i.RenderKeySalt,
		&i.ExpiresAt,
		&i.ResponseLimit,
		&i.ResponseTtlDays,
		&i.BurnAfterReading,
		&i.WorkspaceID,
		&i.CreatedByAccountID,
		&i.WorkspaceWrappedFormKey,
		&i.UseCustomDomain,
	)
	return i, err
}

const getFormPublic = `-- name: GetFormPublic :one
SELECT id, status, schema_version, response_count, render_encrypted_schema, public_form_key, expires_at, response_limit
FROM forms WHERE id = $1
`

type GetFormPublicRow struct {
	ID                    string
	Status                string
	SchemaVersion         int32
	ResponseCount         int32
	RenderEncryptedSchema []byte
	PublicFormKey         []byte
	ExpiresAt             pgtype.Date
	ResponseLimit         pgtype.Int4
}

func (q *Queries) GetFormPublic(ctx context.Context, id string) (GetFormPublicRow, error) {
	row := q.db.QueryRow(ctx, getFormPublic, id)
	var i GetFormPublicRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SchemaVersion,
		&i.ResponseCount,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
		&i.ExpiresAt,
		&i.ResponseLimit,
	)
	return i, err
}

const getFormWorkspaceID = `-- name: GetFormWorkspaceID :one
SELECT workspace_id FROM forms WHERE id = $1
`

func (q *Queries) GetFormWorkspaceID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getFormWorkspaceID, id)
	var workspace_id string
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT encrypted_schema FROM form_schema_versions
WHERE form_id = $1 AND version = $2
`

type GetSchemaVersionParams struct {
	FormID  string
	Version int32
}

func (q *Queries) GetSchemaVersion(ctx context.Context, arg GetSchemaVersionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion, arg.FormID, arg.Version)
	var encrypted_schema []byte
	err := row.Scan(&encrypted_schema)
	return encrypted_schema, err
}

const incrementResponseCount = `-- name: IncrementResponseCount :one
UPDATE forms
SET response_count = response_count + 1
WHERE id = $1
  AND (response_limit IS NULL OR response_count < response_limit)
  AND (expires_at IS NULL OR expires_at >= CURRENT_DATE)
  AND status = 'open'
RETURNING response_count
`

func (q *Queries) IncrementResponseCount(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementResponseCount, id)
	var response_count int32
	err := row.Scan(&response_count)
	return response_count, err
}

const insertSchemaVersion = `-- name: InsertSchemaVersion :exec
INSERT INTO form_schema_versions (form_id, version, encrypted_schema, created_at)
VALUES ($1, $2, $3, NOW())
`

type InsertSchemaVersionParams struct {
	FormID          string
	Version         int32
	EncryptedSchema []byte
}

func (q *Queries) InsertSchemaVersion(ctx context.Context, arg InsertSchemaVersionParams) error {
	_, err := q.db.Exec(ctx, insertSchemaVersion, arg.FormID, arg.Version, arg.EncryptedSchema)
	return err
}

const listFormsByWorkspace = `-- name: ListFormsByWorkspace :many
SELECT id, status, schema_version, response_count, created_at, updated_at, expires_at, response_limit, response_ttl_days, burn_after_reading, use_custom_domain
FROM forms WHERE workspace_id = $1 ORDER BY created_at DESC
`

type ListFormsByWorkspaceRow struct {
	ID               string
	Status           string
	SchemaVersion    int32
	ResponseCount    int32
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	ExpiresAt        pgtype.Date
	ResponseLimit    pgtype.Int4
	ResponseTtlDays  pgtype.Int4
	BurnAfterReading bool
	UseCustomDomain  bool
}

func (q *Queries) ListFormsByWorkspace(ctx context.Context, workspaceID string) ([]ListFormsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listFormsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsByWorkspaceRow
	for rows.Next() {
		var i ListFormsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SchemaVersion,
			&i.ResponseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.ResponseLimit,
			&i.ResponseTtlDays,
			&i.BurnAfterReading,
			&i.UseCustomDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemaVersions = `-- name: ListSchemaVersions :many
SELECT version, created_at FROM form_schema_versions
WHERE form_id = $1 ORDER BY version DESC
`

type ListSchemaVersionsRow struct {
	Version   int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListSchemaVersions(ctx context.Context, formID string) ([]ListSchemaVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSchemaVersions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchemaVersionsRow
	for rows.Next() {
		var i ListSchemaVersionsRow
		if err := rows.Scan(&i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFormCustomDomain = `-- name: SetFormCustomDomain :exec
UPDATE forms SET use_custom_domain = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type SetFormCustomDomainParams struct {
	ID              string
	WorkspaceID     string
	UseCustomDomain bool
}

func (q *Queries) SetFormCustomDomain(ctx context.Context, arg SetFormCustomDomainParams) error {
	_, err := q.db.Exec(ctx, setFormCustomDomain, arg.ID, arg.WorkspaceID, arg.UseCustomDomain)
	return err
}

const setWorkspaceFormKey = `-- name: SetWorkspaceFormKey :exec
UPDATE forms
SET workspace_wrapped_form_key = $3
WHERE id = $1 AND workspace_id = $2
`

type SetWorkspaceFormKeyParams struct {
	ID                      string
	WorkspaceID             string
	WorkspaceWrappedFormKey []byte
}

func (q *Queries) SetWorkspaceFormKey(ctx context.Context, arg SetWorkspaceFormKeyParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceFormKey, arg.ID, arg.WorkspaceID, arg.WorkspaceWrappedFormKey)
	return err
}

const updateFormExpiration = `-- name: UpdateFormExpiration :exec
UPDATE forms
SET expires_at          = $3,
    response_limit      = $4,
    response_ttl_days   = $5,
    burn_after_reading  = $6,
    updated_at          = NOW()
WHERE id = $1 AND workspace_id = $2
`

type UpdateFormExpirationParams struct {
	ID               string
	WorkspaceID      string
	ExpiresAt        pgtype.Date
	ResponseLimit    pgtype.Int4
	ResponseTtlDays  pgtype.Int4
	BurnAfterReading bool
}

func (q *Queries) UpdateFormExpiration(ctx context.Context, arg UpdateFormExpirationParams) error {
	_, err := q.db.Exec(ctx, updateFormExpiration,
		arg.ID,
		arg.WorkspaceID,
		arg.ExpiresAt,
		arg.ResponseLimit,
		arg.ResponseTtlDays,
		arg.BurnAfterReading,
	)
	return err
}

const updateFormSchema = `-- name: UpdateFormSchema :one
UPDATE forms
SET encrypted_schema = $3,
    render_encrypted_schema = $4,
    render_key_salt = $5,
    schema_version = schema_version + 1,
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
RETURNING schema_version
`

type UpdateFormSchemaParams struct {
	ID                    string
	WorkspaceID           string
	EncryptedSchema       []byte
	RenderEncryptedSchema []byte
	RenderKeySalt         []byte
}

func (q *Queries) UpdateFormSchema(ctx context.Context, arg UpdateFormSchemaParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateFormSchema,
		arg.ID,
		arg.WorkspaceID,
		arg.EncryptedSchema,
		arg.RenderEncryptedSchema,
		arg.RenderKeySalt,
	)
	var schema_version int32
	err := row.Scan(&schema_version)
	return schema_version, err
}

const updateFormStatus = `-- name: UpdateFormStatus :exec
UPDATE forms SET status = $3, updated_at = NOW()
WHERE id = $1 AND workspace_id = $2
`

type UpdateFormStatusParams struct {
	ID          string
	WorkspaceID string
	Status      string
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) error {
	_, err := q.db.Exec(ctx, updateFormStatus, arg.ID, arg.WorkspaceID, arg.Status)
	return err
}
