// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forms.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createForm = `-- name: CreateForm :one
INSERT INTO forms (
    id, account_id, created_at, updated_at, status, schema_version,
    response_count, encrypted_schema, render_encrypted_schema, public_form_key,
    render_key_salt
) VALUES (
    $1, $2, CURRENT_DATE, CURRENT_DATE, 'open', 1, 0, $3, $4, $5, $6
) RETURNING id, account_id, created_at, updated_at, status, schema_version, response_count, encrypted_schema, render_encrypted_schema, public_form_key, render_key_salt
`

type CreateFormParams struct {
	ID                    string
	AccountID             string
	EncryptedSchema       []byte
	RenderEncryptedSchema []byte
	PublicFormKey         []byte
	RenderKeySalt         []byte
}

func (q *Queries) CreateForm(ctx context.Context, arg CreateFormParams) (Form, error) {
	row := q.db.QueryRow(ctx, createForm,
		arg.ID,
		arg.AccountID,
		arg.EncryptedSchema,
		arg.RenderEncryptedSchema,
		arg.PublicFormKey,
		arg.RenderKeySalt,
	)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.SchemaVersion,
		&i.ResponseCount,
		&i.EncryptedSchema,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
		&i.RenderKeySalt,
	)
	return i, err
}

const deleteForm = `-- name: DeleteForm :exec
DELETE FROM forms WHERE id = $1 AND account_id = $2
`

type DeleteFormParams struct {
	ID        string
	AccountID string
}

func (q *Queries) DeleteForm(ctx context.Context, arg DeleteFormParams) error {
	_, err := q.db.Exec(ctx, deleteForm, arg.ID, arg.AccountID)
	return err
}

const getFormByOwner = `-- name: GetFormByOwner :one
SELECT id, account_id, created_at, updated_at, status, schema_version, response_count, encrypted_schema, render_encrypted_schema, public_form_key, render_key_salt FROM forms WHERE id = $1 AND account_id = $2
`

type GetFormByOwnerParams struct {
	ID        string
	AccountID string
}

func (q *Queries) GetFormByOwner(ctx context.Context, arg GetFormByOwnerParams) (Form, error) {
	row := q.db.QueryRow(ctx, getFormByOwner, arg.ID, arg.AccountID)
	var i Form
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.SchemaVersion,
		&i.ResponseCount,
		&i.EncryptedSchema,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
		&i.RenderKeySalt,
	)
	return i, err
}

const getFormPublic = `-- name: GetFormPublic :one
SELECT id, status, schema_version, render_encrypted_schema, public_form_key
FROM forms WHERE id = $1
`

type GetFormPublicRow struct {
	ID                    string
	Status                string
	SchemaVersion         int32
	RenderEncryptedSchema []byte
	PublicFormKey         []byte
}

func (q *Queries) GetFormPublic(ctx context.Context, id string) (GetFormPublicRow, error) {
	row := q.db.QueryRow(ctx, getFormPublic, id)
	var i GetFormPublicRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.SchemaVersion,
		&i.RenderEncryptedSchema,
		&i.PublicFormKey,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT encrypted_schema FROM form_schema_versions
WHERE form_id = $1 AND version = $2
`

type GetSchemaVersionParams struct {
	FormID  string
	Version int32
}

func (q *Queries) GetSchemaVersion(ctx context.Context, arg GetSchemaVersionParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSchemaVersion, arg.FormID, arg.Version)
	var encrypted_schema []byte
	err := row.Scan(&encrypted_schema)
	return encrypted_schema, err
}

const incrementResponseCount = `-- name: IncrementResponseCount :exec
UPDATE forms SET response_count = response_count + $2 WHERE id = $1
`

type IncrementResponseCountParams struct {
	ID            string
	ResponseCount int32
}

func (q *Queries) IncrementResponseCount(ctx context.Context, arg IncrementResponseCountParams) error {
	_, err := q.db.Exec(ctx, incrementResponseCount, arg.ID, arg.ResponseCount)
	return err
}

const insertSchemaVersion = `-- name: InsertSchemaVersion :exec
INSERT INTO form_schema_versions (form_id, version, encrypted_schema, created_at)
VALUES ($1, $2, $3, CURRENT_DATE)
`

type InsertSchemaVersionParams struct {
	FormID          string
	Version         int32
	EncryptedSchema []byte
}

func (q *Queries) InsertSchemaVersion(ctx context.Context, arg InsertSchemaVersionParams) error {
	_, err := q.db.Exec(ctx, insertSchemaVersion, arg.FormID, arg.Version, arg.EncryptedSchema)
	return err
}

const listFormsByAccount = `-- name: ListFormsByAccount :many
SELECT id, status, schema_version, response_count, created_at, updated_at
FROM forms WHERE account_id = $1 ORDER BY created_at DESC
`

type ListFormsByAccountRow struct {
	ID            string
	Status        string
	SchemaVersion int32
	ResponseCount int32
	CreatedAt     pgtype.Date
	UpdatedAt     pgtype.Date
}

func (q *Queries) ListFormsByAccount(ctx context.Context, accountID string) ([]ListFormsByAccountRow, error) {
	rows, err := q.db.Query(ctx, listFormsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsByAccountRow
	for rows.Next() {
		var i ListFormsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.SchemaVersion,
			&i.ResponseCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemaVersions = `-- name: ListSchemaVersions :many
SELECT version, created_at FROM form_schema_versions
WHERE form_id = $1 ORDER BY version DESC
`

type ListSchemaVersionsRow struct {
	Version   int32
	CreatedAt pgtype.Date
}

func (q *Queries) ListSchemaVersions(ctx context.Context, formID string) ([]ListSchemaVersionsRow, error) {
	rows, err := q.db.Query(ctx, listSchemaVersions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchemaVersionsRow
	for rows.Next() {
		var i ListSchemaVersionsRow
		if err := rows.Scan(&i.Version, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFormSchema = `-- name: UpdateFormSchema :one
UPDATE forms
SET encrypted_schema = $3,
    render_encrypted_schema = $4,
    render_key_salt = $5,
    schema_version = schema_version + 1,
    updated_at = CURRENT_DATE
WHERE id = $1 AND account_id = $2
RETURNING schema_version
`

type UpdateFormSchemaParams struct {
	ID                    string
	AccountID             string
	EncryptedSchema       []byte
	RenderEncryptedSchema []byte
	RenderKeySalt         []byte
}

func (q *Queries) UpdateFormSchema(ctx context.Context, arg UpdateFormSchemaParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateFormSchema,
		arg.ID,
		arg.AccountID,
		arg.EncryptedSchema,
		arg.RenderEncryptedSchema,
		arg.RenderKeySalt,
	)
	var schema_version int32
	err := row.Scan(&schema_version)
	return schema_version, err
}

const updateFormStatus = `-- name: UpdateFormStatus :exec
UPDATE forms SET status = $3, updated_at = CURRENT_DATE
WHERE id = $1 AND account_id = $2
`

type UpdateFormStatusParams struct {
	ID        string
	AccountID string
	Status    string
}

func (q *Queries) UpdateFormStatus(ctx context.Context, arg UpdateFormStatusParams) error {
	_, err := q.db.Exec(ctx, updateFormStatus, arg.ID, arg.AccountID, arg.Status)
	return err
}
