// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package queries

import (
	"context"
)

const getIdentityKey = `-- name: GetIdentityKey :one
SELECT identity_public_key, wrapped_identity_private_key
FROM account_identity_keys WHERE account_id = $1
`

type GetIdentityKeyRow struct {
	IdentityPublicKey         []byte
	WrappedIdentityPrivateKey []byte
}

func (q *Queries) GetIdentityKey(ctx context.Context, accountID string) (GetIdentityKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdentityKey, accountID)
	var i GetIdentityKeyRow
	err := row.Scan(&i.IdentityPublicKey, &i.WrappedIdentityPrivateKey)
	return i, err
}

const getIdentityPublicKey = `-- name: GetIdentityPublicKey :one
SELECT identity_public_key
FROM account_identity_keys WHERE account_id = $1
`

func (q *Queries) GetIdentityPublicKey(ctx context.Context, accountID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getIdentityPublicKey, accountID)
	var identity_public_key []byte
	err := row.Scan(&identity_public_key)
	return identity_public_key, err
}

const upsertIdentityKey = `-- name: UpsertIdentityKey :exec
INSERT INTO account_identity_keys (account_id, identity_public_key, wrapped_identity_private_key, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (account_id) DO UPDATE
  SET identity_public_key          = EXCLUDED.identity_public_key,
      wrapped_identity_private_key = EXCLUDED.wrapped_identity_private_key,
      created_at                   = EXCLUDED.created_at
`

type UpsertIdentityKeyParams struct {
	AccountID                 string
	IdentityPublicKey         []byte
	WrappedIdentityPrivateKey []byte
}

func (q *Queries) UpsertIdentityKey(ctx context.Context, arg UpsertIdentityKeyParams) error {
	_, err := q.db.Exec(ctx, upsertIdentityKey, arg.AccountID, arg.IdentityPublicKey, arg.WrappedIdentityPrivateKey)
	return err
}
