// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE workspace_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO workspace_invitations (id, workspace_id, invited_by_account_id, email, role, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, invited_by_account_id, email, role, expires_at, created_at
`

type CreateInvitationParams struct {
	ID                 string
	WorkspaceID        string
	InvitedByAccountID string
	Email              string
	Role               string
	TokenHash          string
	ExpiresAt          pgtype.Timestamptz
}

type CreateInvitationRow struct {
	ID                 string
	WorkspaceID        string
	InvitedByAccountID string
	Email              string
	Role               string
	ExpiresAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.InvitedByAccountID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedByAccountID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM workspace_invitations WHERE id = $1 AND workspace_id = $2
`

type DeleteInvitationParams struct {
	ID          string
	WorkspaceID string
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.WorkspaceID)
	return err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT wi.id, wi.workspace_id, wi.invited_by_account_id, wi.email, wi.role,
       wi.expires_at, wi.accepted_at, wi.created_at,
       w.name AS workspace_name, a.username AS inviter_username
FROM workspace_invitations wi
JOIN workspaces w ON w.id = wi.workspace_id
JOIN accounts a ON a.id = wi.invited_by_account_id
WHERE wi.token_hash = $1
`

type GetInvitationByTokenHashRow struct {
	ID                 string
	WorkspaceID        string
	InvitedByAccountID string
	Email              string
	Role               string
	ExpiresAt          pgtype.Timestamptz
	AcceptedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	WorkspaceName      string
	InviterUsername    pgtype.Text
}

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (GetInvitationByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i GetInvitationByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedByAccountID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.WorkspaceName,
		&i.InviterUsername,
	)
	return i, err
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, email, role, expires_at, created_at
FROM workspace_invitations
WHERE workspace_id = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
`

type ListPendingInvitationsRow struct {
	ID        string
	Email     string
	Role      string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListPendingInvitations(ctx context.Context, workspaceID string) ([]ListPendingInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingInvitationsRow
	for rows.Next() {
		var i ListPendingInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
