// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	CreatedAt             pgtype.Date
	CredentialID          []byte
	PublicKey             []byte
	PrfSalt               []byte
	WrappedMasterKey      []byte
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
}

type RecoveryCode struct {
	ID        string
	AccountID string
	CodeHash  []byte
	Used      bool
	CreatedAt pgtype.Date
}

type Session struct {
	ID        string
	AccountID string
	TokenHash []byte
	CreatedAt pgtype.Date
	LastSeen  pgtype.Date
}
