// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string
	CreatedAt             pgtype.Timestamptz
	RecoveryWrappedMaster []byte
	RecoveryVerifier      []byte
	Username              pgtype.Text
	UpdatedAt             pgtype.Timestamptz
}

type AccountIdentityKey struct {
	AccountID                 string
	IdentityPublicKey         []byte
	WrappedIdentityPrivateKey []byte
	CreatedAt                 pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type Credential struct {
	ID               string
	AccountID        string
	CredentialID     []byte
	PublicKey        []byte
	PrfSalt          []byte
	WrappedMasterKey []byte
	BackupEligible   bool
	Name             string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type Form struct {
	ID                      string
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	Status                  string
	SchemaVersion           int32
	ResponseCount           int32
	EncryptedSchema         []byte
	RenderEncryptedSchema   []byte
	PublicFormKey           []byte
	RenderKeySalt           []byte
	ExpiresAt               pgtype.Date
	ResponseLimit           pgtype.Int4
	ResponseTtlDays         pgtype.Int4
	BurnAfterReading        bool
	WorkspaceID             string
	CreatedByAccountID      string
	WorkspaceWrappedFormKey []byte
	UseCustomDomain         bool
}

type FormSchemaVersion struct {
	FormID          string
	Version         int32
	EncryptedSchema []byte
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type RecoveryCode struct {
	ID        string
	AccountID string
	CodeHash  []byte
	Used      bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Response struct {
	ID                 string
	FormID             string
	ReceivedAt         pgtype.Timestamptz
	SchemaVersion      int32
	EncryptedData      []byte
	EphemeralPublicKey []byte
	ExpiresAt          pgtype.Timestamptz
	ReadAt             pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Session struct {
	ID           string
	AccountID    string
	TokenHash    []byte
	CreatedAt    pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
	CredentialID []byte
	UserAgent    string
	UpdatedAt    pgtype.Timestamptz
}

type Workspace struct {
	ID                   string
	Name                 string
	Slug                 string
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	Plan                 string
	PlanStatus           string
	PlanPeriodEnd        pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	CustomDomain         pgtype.Text
	CustomDomainVerified bool
}

type WorkspaceInvitation struct {
	ID                 string
	WorkspaceID        string
	InvitedByAccountID string
	Email              string
	Role               string
	TokenHash          string
	ExpiresAt          pgtype.Timestamptz
	AcceptedAt         pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID string
	AccountID   string
	Role        string
	JoinedAt    pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type WorkspaceMemberKey struct {
	WorkspaceID         string
	AccountID           string
	WrappedWorkspaceKey []byte
	EphemeralPublicKey  []byte
	GrantedByAccountID  string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
