// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResponse = `-- name: CreateResponse :exec
INSERT INTO responses (id, form_id, received_at, schema_version, encrypted_data, ephemeral_public_key)
VALUES ($1, $2, CURRENT_DATE, $3, $4, $5)
`

type CreateResponseParams struct {
	ID                 string
	FormID             string
	SchemaVersion      int32
	EncryptedData      []byte
	EphemeralPublicKey []byte
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) error {
	_, err := q.db.Exec(ctx, createResponse,
		arg.ID,
		arg.FormID,
		arg.SchemaVersion,
		arg.EncryptedData,
		arg.EphemeralPublicKey,
	)
	return err
}

const deleteResponse = `-- name: DeleteResponse :exec
DELETE FROM responses WHERE id = $1 AND form_id = $2
`

type DeleteResponseParams struct {
	ID     string
	FormID string
}

func (q *Queries) DeleteResponse(ctx context.Context, arg DeleteResponseParams) error {
	_, err := q.db.Exec(ctx, deleteResponse, arg.ID, arg.FormID)
	return err
}

const getResponse = `-- name: GetResponse :one
SELECT id, form_id, received_at, schema_version, encrypted_data, ephemeral_public_key
FROM responses WHERE id = $1 AND form_id = $2
`

type GetResponseParams struct {
	ID     string
	FormID string
}

func (q *Queries) GetResponse(ctx context.Context, arg GetResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, getResponse, arg.ID, arg.FormID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ReceivedAt,
		&i.SchemaVersion,
		&i.EncryptedData,
		&i.EphemeralPublicKey,
	)
	return i, err
}

const listResponsesAfter = `-- name: ListResponsesAfter :many
SELECT id, form_id, received_at, schema_version, encrypted_data, ephemeral_public_key
FROM responses
WHERE form_id = $1
  AND (received_at < $2 OR (received_at = $2 AND id < $3))
ORDER BY received_at DESC, id DESC
LIMIT $4
`

type ListResponsesAfterParams struct {
	FormID     string
	ReceivedAt pgtype.Date
	ID         string
	Limit      int32
}

func (q *Queries) ListResponsesAfter(ctx context.Context, arg ListResponsesAfterParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesAfter,
		arg.FormID,
		arg.ReceivedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.EncryptedData,
			&i.EphemeralPublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsesFirst = `-- name: ListResponsesFirst :many
SELECT id, form_id, received_at, schema_version, encrypted_data, ephemeral_public_key
FROM responses
WHERE form_id = $1
ORDER BY received_at DESC, id DESC
LIMIT $2
`

type ListResponsesFirstParams struct {
	FormID string
	Limit  int32
}

func (q *Queries) ListResponsesFirst(ctx context.Context, arg ListResponsesFirstParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesFirst, arg.FormID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.EncryptedData,
			&i.EphemeralPublicKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
