// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: responses.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExpiredResponses = `-- name: DeleteExpiredResponses :exec
DELETE FROM responses
WHERE (expires_at IS NOT NULL AND expires_at < NOW())
   OR (read_at IS NOT NULL AND form_id IN (
         SELECT id FROM forms WHERE burn_after_reading = true
       ))
`

func (q *Queries) DeleteExpiredResponses(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredResponses)
	return err
}

const deleteResponse = `-- name: DeleteResponse :exec
DELETE FROM responses WHERE id = $1 AND form_id = $2
`

type DeleteResponseParams struct {
	ID     string
	FormID string
}

func (q *Queries) DeleteResponse(ctx context.Context, arg DeleteResponseParams) error {
	_, err := q.db.Exec(ctx, deleteResponse, arg.ID, arg.FormID)
	return err
}

const getResponse = `-- name: GetResponse :one
SELECT responses.id, responses.form_id, responses.received_at, responses.schema_version, responses.encrypted_data, responses.ephemeral_public_key, responses.expires_at, responses.read_at, responses.updated_at
FROM responses
WHERE responses.id = $1 AND responses.form_id = $2
  AND (responses.expires_at IS NULL OR responses.expires_at > NOW())
  AND (responses.read_at IS NULL OR responses.form_id NOT IN (SELECT f.id FROM forms f WHERE f.burn_after_reading = true))
`

type GetResponseParams struct {
	ID     string
	FormID string
}

func (q *Queries) GetResponse(ctx context.Context, arg GetResponseParams) (Response, error) {
	row := q.db.QueryRow(ctx, getResponse, arg.ID, arg.FormID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.ReceivedAt,
		&i.SchemaVersion,
		&i.EncryptedData,
		&i.EphemeralPublicKey,
		&i.ExpiresAt,
		&i.ReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertResponseWithTTL = `-- name: InsertResponseWithTTL :exec
INSERT INTO responses (id, form_id, received_at, schema_version, encrypted_data, ephemeral_public_key, expires_at)
SELECT $1, $2, NOW(), $3, $4, $5,
       CASE WHEN f.response_ttl_days IS NOT NULL
            THEN NOW() + (f.response_ttl_days || ' days')::INTERVAL
            ELSE NULL END
FROM forms f
WHERE f.id = $2
`

type InsertResponseWithTTLParams struct {
	ID                 string
	FormID             string
	SchemaVersion      int32
	EncryptedData      []byte
	EphemeralPublicKey []byte
}

func (q *Queries) InsertResponseWithTTL(ctx context.Context, arg InsertResponseWithTTLParams) error {
	_, err := q.db.Exec(ctx, insertResponseWithTTL,
		arg.ID,
		arg.FormID,
		arg.SchemaVersion,
		arg.EncryptedData,
		arg.EphemeralPublicKey,
	)
	return err
}

const listResponsesAfter = `-- name: ListResponsesAfter :many
SELECT responses.id, responses.form_id, responses.received_at, responses.schema_version, responses.encrypted_data, responses.ephemeral_public_key, responses.expires_at, responses.read_at, responses.updated_at
FROM responses
WHERE responses.form_id = $1
  AND (responses.received_at < $2 OR (responses.received_at = $2 AND responses.id < $3))
  AND (responses.expires_at IS NULL OR responses.expires_at > NOW())
  AND (responses.read_at IS NULL OR responses.form_id NOT IN (SELECT f.id FROM forms f WHERE f.burn_after_reading = true))
ORDER BY responses.received_at DESC, responses.id DESC
LIMIT $4
`

type ListResponsesAfterParams struct {
	FormID     string
	ReceivedAt pgtype.Timestamptz
	ID         string
	Limit      int32
}

func (q *Queries) ListResponsesAfter(ctx context.Context, arg ListResponsesAfterParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesAfter,
		arg.FormID,
		arg.ReceivedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.EncryptedData,
			&i.EphemeralPublicKey,
			&i.ExpiresAt,
			&i.ReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResponsesFirst = `-- name: ListResponsesFirst :many
SELECT responses.id, responses.form_id, responses.received_at, responses.schema_version, responses.encrypted_data, responses.ephemeral_public_key, responses.expires_at, responses.read_at, responses.updated_at
FROM responses
WHERE responses.form_id = $1
  AND (responses.expires_at IS NULL OR responses.expires_at > NOW())
  AND (responses.read_at IS NULL OR responses.form_id NOT IN (SELECT f.id FROM forms f WHERE f.burn_after_reading = true))
ORDER BY responses.received_at DESC, responses.id DESC
LIMIT $2
`

type ListResponsesFirstParams struct {
	FormID string
	Limit  int32
}

func (q *Queries) ListResponsesFirst(ctx context.Context, arg ListResponsesFirstParams) ([]Response, error) {
	rows, err := q.db.Query(ctx, listResponsesFirst, arg.FormID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.ReceivedAt,
			&i.SchemaVersion,
			&i.EncryptedData,
			&i.EphemeralPublicKey,
			&i.ExpiresAt,
			&i.ReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markResponsesRead = `-- name: MarkResponsesRead :exec
UPDATE responses
SET read_at = NOW(), updated_at = NOW()
WHERE form_id = $1
  AND id = ANY($2::text[])
  AND read_at IS NULL
`

type MarkResponsesReadParams struct {
	FormID  string
	Column2 []string
}

func (q *Queries) MarkResponsesRead(ctx context.Context, arg MarkResponsesReadParams) error {
	_, err := q.db.Exec(ctx, markResponsesRead, arg.FormID, arg.Column2)
	return err
}
