// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnerWorkspaces = `-- name: CountOwnerWorkspaces :one
SELECT COUNT(*) FROM workspace_members
WHERE account_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnerWorkspaces(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerWorkspaces, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug, plan, plan_status, created_at)
VALUES ($1, $2, $3, 'free', 'active', now())
RETURNING id, name, slug, stripe_customer_id, stripe_subscription_id, plan, plan_status, plan_period_end, created_at
`

type CreateWorkspaceParams struct {
	ID   string
	Name string
	Slug string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, account_id, role, joined_at)
VALUES ($1, $2, $3, now())
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID string
	AccountID   string
	Role        string
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, createWorkspaceMember, arg.WorkspaceID, arg.AccountID, arg.Role)
	return err
}

const getMembersWithoutWorkspaceKey = `-- name: GetMembersWithoutWorkspaceKey :many
SELECT wm.account_id
FROM workspace_members wm
LEFT JOIN workspace_member_keys wmk
  ON wmk.workspace_id = wm.workspace_id AND wmk.account_id = wm.account_id
WHERE wm.workspace_id = $1 AND wmk.account_id IS NULL
`

func (q *Queries) GetMembersWithoutWorkspaceKey(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMembersWithoutWorkspaceKey, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalWorkspace = `-- name: GetPersonalWorkspace :one
SELECT w.id, w.name, w.slug, w.plan, w.plan_status, w.plan_period_end, w.created_at
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.account_id = $1 AND wm.role = 'owner'
ORDER BY w.created_at ASC
LIMIT 1
`

type GetPersonalWorkspaceRow struct {
	ID            string
	Name          string
	Slug          string
	Plan          string
	PlanStatus    string
	PlanPeriodEnd pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetPersonalWorkspace(ctx context.Context, accountID string) (GetPersonalWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspace, accountID)
	var i GetPersonalWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, plan, plan_status, plan_period_end, created_at
FROM workspaces WHERE id = $1
`

type GetWorkspaceByIDRow struct {
	ID            string
	Name          string
	Slug          string
	Plan          string
	PlanStatus    string
	PlanPeriodEnd pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, account_id, role, joined_at
FROM workspace_members WHERE workspace_id = $1 AND account_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID string
	AccountID   string
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getWorkspaceMemberKey = `-- name: GetWorkspaceMemberKey :one
SELECT wrapped_workspace_key, ephemeral_public_key
FROM workspace_member_keys
WHERE workspace_id = $1 AND account_id = $2
`

type GetWorkspaceMemberKeyParams struct {
	WorkspaceID string
	AccountID   string
}

type GetWorkspaceMemberKeyRow struct {
	WrappedWorkspaceKey []byte
	EphemeralPublicKey  []byte
}

func (q *Queries) GetWorkspaceMemberKey(ctx context.Context, arg GetWorkspaceMemberKeyParams) (GetWorkspaceMemberKeyRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberKey, arg.WorkspaceID, arg.AccountID)
	var i GetWorkspaceMemberKeyRow
	err := row.Scan(&i.WrappedWorkspaceKey, &i.EphemeralPublicKey)
	return i, err
}

const upsertWorkspaceMemberKey = `-- name: UpsertWorkspaceMemberKey :exec
INSERT INTO workspace_member_keys (workspace_id, account_id, wrapped_workspace_key, ephemeral_public_key, granted_by_account_id, created_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (workspace_id, account_id) DO UPDATE
  SET wrapped_workspace_key = EXCLUDED.wrapped_workspace_key,
      ephemeral_public_key  = EXCLUDED.ephemeral_public_key,
      granted_by_account_id = EXCLUDED.granted_by_account_id,
      created_at            = EXCLUDED.created_at
`

type UpsertWorkspaceMemberKeyParams struct {
	WorkspaceID         string
	AccountID           string
	WrappedWorkspaceKey []byte
	EphemeralPublicKey  []byte
	GrantedByAccountID  string
}

func (q *Queries) UpsertWorkspaceMemberKey(ctx context.Context, arg UpsertWorkspaceMemberKeyParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceMemberKey,
		arg.WorkspaceID,
		arg.AccountID,
		arg.WrappedWorkspaceKey,
		arg.EphemeralPublicKey,
		arg.GrantedByAccountID,
	)
	return err
}
