// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearWorkspaceCustomDomain = `-- name: ClearWorkspaceCustomDomain :exec
UPDATE workspaces SET custom_domain = NULL, custom_domain_verified = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ClearWorkspaceCustomDomain(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, clearWorkspaceCustomDomain, id)
	return err
}

const countNonOwnerMembers = `-- name: CountNonOwnerMembers :one
SELECT COUNT(*) FROM workspace_members WHERE workspace_id = $1 AND role != 'owner'
`

func (q *Queries) CountNonOwnerMembers(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countNonOwnerMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerWorkspaces = `-- name: CountOwnerWorkspaces :one
SELECT COUNT(*) FROM workspace_members
WHERE account_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwnerWorkspaces(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerWorkspaces, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceMembers = `-- name: CountWorkspaceMembers :one
SELECT COUNT(*) FROM workspace_members WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceMembers(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceMembers, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT COUNT(*) FROM workspace_members WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, slug, plan, plan_status, created_at)
VALUES ($1, $2, $3, 'free', 'active', NOW())
RETURNING id, name, slug, stripe_customer_id, stripe_subscription_id, plan, plan_status, plan_period_end, created_at, updated_at, custom_domain, custom_domain_verified
`

type CreateWorkspaceParams struct {
	ID   string
	Name string
	Slug string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomDomain,
		&i.CustomDomainVerified,
	)
	return i, err
}

const createWorkspaceMember = `-- name: CreateWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, account_id, role, joined_at)
VALUES ($1, $2, $3, NOW())
`

type CreateWorkspaceMemberParams struct {
	WorkspaceID string
	AccountID   string
	Role        string
}

func (q *Queries) CreateWorkspaceMember(ctx context.Context, arg CreateWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, createWorkspaceMember, arg.WorkspaceID, arg.AccountID, arg.Role)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members WHERE workspace_id = $1 AND account_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID string
	AccountID   string
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	return err
}

const deleteWorkspaceMemberKey = `-- name: DeleteWorkspaceMemberKey :exec
DELETE FROM workspace_member_keys WHERE workspace_id = $1 AND account_id = $2
`

type DeleteWorkspaceMemberKeyParams struct {
	WorkspaceID string
	AccountID   string
}

func (q *Queries) DeleteWorkspaceMemberKey(ctx context.Context, arg DeleteWorkspaceMemberKeyParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMemberKey, arg.WorkspaceID, arg.AccountID)
	return err
}

const getMembersWithoutWorkspaceKey = `-- name: GetMembersWithoutWorkspaceKey :many
SELECT wm.account_id
FROM workspace_members wm
LEFT JOIN workspace_member_keys wmk
  ON wmk.workspace_id = wm.workspace_id AND wmk.account_id = wm.account_id
WHERE wm.workspace_id = $1 AND wmk.account_id IS NULL
`

func (q *Queries) GetMembersWithoutWorkspaceKey(ctx context.Context, workspaceID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getMembersWithoutWorkspaceKey, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembersWithoutWorkspaceKeyWithUsername = `-- name: GetMembersWithoutWorkspaceKeyWithUsername :many
SELECT wm.account_id, a.username
FROM workspace_members wm
LEFT JOIN workspace_member_keys wmk
  ON wmk.workspace_id = wm.workspace_id AND wmk.account_id = wm.account_id
JOIN accounts a ON a.id = wm.account_id
WHERE wm.workspace_id = $1 AND wmk.account_id IS NULL
`

type GetMembersWithoutWorkspaceKeyWithUsernameRow struct {
	AccountID string
	Username  pgtype.Text
}

func (q *Queries) GetMembersWithoutWorkspaceKeyWithUsername(ctx context.Context, workspaceID string) ([]GetMembersWithoutWorkspaceKeyWithUsernameRow, error) {
	rows, err := q.db.Query(ctx, getMembersWithoutWorkspaceKeyWithUsername, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMembersWithoutWorkspaceKeyWithUsernameRow
	for rows.Next() {
		var i GetMembersWithoutWorkspaceKeyWithUsernameRow
		if err := rows.Scan(&i.AccountID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonalWorkspace = `-- name: GetPersonalWorkspace :one
SELECT w.id, w.name, w.slug, w.plan, w.plan_status, w.plan_period_end, w.created_at
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.account_id = $1 AND wm.role = 'owner'
ORDER BY w.created_at ASC
LIMIT 1
`

type GetPersonalWorkspaceRow struct {
	ID            string
	Name          string
	Slug          string
	Plan          string
	PlanStatus    string
	PlanPeriodEnd pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetPersonalWorkspace(ctx context.Context, accountID string) (GetPersonalWorkspaceRow, error) {
	row := q.db.QueryRow(ctx, getPersonalWorkspace, accountID)
	var i GetPersonalWorkspaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByCustomDomain = `-- name: GetWorkspaceByCustomDomain :one
SELECT id FROM workspaces WHERE custom_domain = $1 AND custom_domain_verified = TRUE
`

func (q *Queries) GetWorkspaceByCustomDomain(ctx context.Context, customDomain pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByCustomDomain, customDomain)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, slug, plan, plan_status, plan_period_end, created_at
FROM workspaces WHERE id = $1
`

type GetWorkspaceByIDRow struct {
	ID            string
	Name          string
	Slug          string
	Plan          string
	PlanStatus    string
	PlanPeriodEnd pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) GetWorkspaceByID(ctx context.Context, id string) (GetWorkspaceByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i GetWorkspaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.PlanPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceCustomDomain = `-- name: GetWorkspaceCustomDomain :one
SELECT custom_domain, custom_domain_verified FROM workspaces WHERE id = $1
`

type GetWorkspaceCustomDomainRow struct {
	CustomDomain         pgtype.Text
	CustomDomainVerified bool
}

func (q *Queries) GetWorkspaceCustomDomain(ctx context.Context, id string) (GetWorkspaceCustomDomainRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceCustomDomain, id)
	var i GetWorkspaceCustomDomainRow
	err := row.Scan(&i.CustomDomain, &i.CustomDomainVerified)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT workspace_id, account_id, role, joined_at, updated_at
FROM workspace_members WHERE workspace_id = $1 AND account_id = $2
`

type GetWorkspaceMemberParams struct {
	WorkspaceID string
	AccountID   string
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.AccountID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.AccountID,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceMemberKey = `-- name: GetWorkspaceMemberKey :one
SELECT wrapped_workspace_key, ephemeral_public_key
FROM workspace_member_keys
WHERE workspace_id = $1 AND account_id = $2
`

type GetWorkspaceMemberKeyParams struct {
	WorkspaceID string
	AccountID   string
}

type GetWorkspaceMemberKeyRow struct {
	WrappedWorkspaceKey []byte
	EphemeralPublicKey  []byte
}

func (q *Queries) GetWorkspaceMemberKey(ctx context.Context, arg GetWorkspaceMemberKeyParams) (GetWorkspaceMemberKeyRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMemberKey, arg.WorkspaceID, arg.AccountID)
	var i GetWorkspaceMemberKeyRow
	err := row.Scan(&i.WrappedWorkspaceKey, &i.EphemeralPublicKey)
	return i, err
}

const listAllVerifiedCustomDomains = `-- name: ListAllVerifiedCustomDomains :many
SELECT custom_domain FROM workspaces WHERE custom_domain IS NOT NULL AND custom_domain_verified = TRUE
`

func (q *Queries) ListAllVerifiedCustomDomains(ctx context.Context) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, listAllVerifiedCustomDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var custom_domain pgtype.Text
		if err := rows.Scan(&custom_domain); err != nil {
			return nil, err
		}
		items = append(items, custom_domain)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberIdentityKeys = `-- name: ListMemberIdentityKeys :many
SELECT wm.account_id, aik.identity_public_key
FROM workspace_members wm
JOIN account_identity_keys aik ON aik.account_id = wm.account_id
WHERE wm.workspace_id = $1
ORDER BY wm.joined_at ASC
`

type ListMemberIdentityKeysRow struct {
	AccountID         string
	IdentityPublicKey []byte
}

func (q *Queries) ListMemberIdentityKeys(ctx context.Context, workspaceID string) ([]ListMemberIdentityKeysRow, error) {
	rows, err := q.db.Query(ctx, listMemberIdentityKeys, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberIdentityKeysRow
	for rows.Next() {
		var i ListMemberIdentityKeysRow
		if err := rows.Scan(&i.AccountID, &i.IdentityPublicKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
  wm.account_id,
  wm.role,
  wm.joined_at,
  a.username,
  CASE WHEN wmk.account_id IS NOT NULL THEN 'active' ELSE 'pending' END AS status,
  (SELECT MAX(s.last_seen) FROM sessions s WHERE s.account_id = wm.account_id) AS last_seen
FROM workspace_members wm
JOIN accounts a ON a.id = wm.account_id
LEFT JOIN workspace_member_keys wmk
  ON wmk.workspace_id = wm.workspace_id AND wmk.account_id = wm.account_id
WHERE wm.workspace_id = $1
ORDER BY wm.joined_at ASC
`

type ListWorkspaceMembersRow struct {
	AccountID string
	Role      string
	JoinedAt  pgtype.Timestamptz
	Username  pgtype.Text
	Status    string
	LastSeen  interface{}
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Status,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByAccount = `-- name: ListWorkspacesByAccount :many
SELECT w.id, w.name, w.slug, w.plan, w.plan_status, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.account_id = $1
ORDER BY w.created_at ASC
`

type ListWorkspacesByAccountRow struct {
	ID         string
	Name       string
	Slug       string
	Plan       string
	PlanStatus string
	Role       string
}

func (q *Queries) ListWorkspacesByAccount(ctx context.Context, accountID string) ([]ListWorkspacesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesByAccountRow
	for rows.Next() {
		var i ListWorkspacesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.PlanStatus,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCustomDomainVerified = `-- name: MarkCustomDomainVerified :exec
UPDATE workspaces SET custom_domain_verified = TRUE, updated_at = NOW()
WHERE custom_domain = $1
`

func (q *Queries) MarkCustomDomainVerified(ctx context.Context, customDomain pgtype.Text) error {
	_, err := q.db.Exec(ctx, markCustomDomainVerified, customDomain)
	return err
}

const renameWorkspace = `-- name: RenameWorkspace :exec
UPDATE workspaces SET name = $2, updated_at = NOW() WHERE id = $1
`

type RenameWorkspaceParams struct {
	ID   string
	Name string
}

func (q *Queries) RenameWorkspace(ctx context.Context, arg RenameWorkspaceParams) error {
	_, err := q.db.Exec(ctx, renameWorkspace, arg.ID, arg.Name)
	return err
}

const setWorkspaceCustomDomain = `-- name: SetWorkspaceCustomDomain :exec
UPDATE workspaces SET custom_domain = $2, custom_domain_verified = FALSE, updated_at = NOW()
WHERE id = $1
`

type SetWorkspaceCustomDomainParams struct {
	ID           string
	CustomDomain pgtype.Text
}

func (q *Queries) SetWorkspaceCustomDomain(ctx context.Context, arg SetWorkspaceCustomDomainParams) error {
	_, err := q.db.Exec(ctx, setWorkspaceCustomDomain, arg.ID, arg.CustomDomain)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members SET role = $3, updated_at = NOW() WHERE workspace_id = $1 AND account_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID string
	AccountID   string
	Role        string
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.AccountID, arg.Role)
	return err
}

const upsertWorkspaceMemberKey = `-- name: UpsertWorkspaceMemberKey :exec
INSERT INTO workspace_member_keys (workspace_id, account_id, wrapped_workspace_key, ephemeral_public_key, granted_by_account_id, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (workspace_id, account_id) DO UPDATE
  SET wrapped_workspace_key = EXCLUDED.wrapped_workspace_key,
      ephemeral_public_key  = EXCLUDED.ephemeral_public_key,
      granted_by_account_id = EXCLUDED.granted_by_account_id,
      updated_at            = NOW()
`

type UpsertWorkspaceMemberKeyParams struct {
	WorkspaceID         string
	AccountID           string
	WrappedWorkspaceKey []byte
	EphemeralPublicKey  []byte
	GrantedByAccountID  pgtype.Text
}

func (q *Queries) UpsertWorkspaceMemberKey(ctx context.Context, arg UpsertWorkspaceMemberKeyParams) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceMemberKey,
		arg.WorkspaceID,
		arg.AccountID,
		arg.WrappedWorkspaceKey,
		arg.EphemeralPublicKey,
		arg.GrantedByAccountID,
	)
	return err
}
