ALTER TABLE workspaces
    ADD COLUMN IF NOT EXISTS custom_domain TEXT UNIQUE,
    ADD COLUMN IF NOT EXISTS custom_domain_verified BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE forms
    ADD COLUMN IF NOT EXISTS use_custom_domain BOOLEAN NOT NULL DEFAULT FALSE;
